name: Build Spring Boot Application

on:
  pull_request:
    branches:
      - develop

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
     - name: Checkout code
       uses: actions/checkout@v4

     - name: Set up JDK 17
       uses: actions/setup-java@v4
       with:
         distribution: 'oracle'
         java-version: 17

     - name: Unit Tests
       run: mvn -B test --file pom.xml

     - name: Build the application
       run: |
         mvn clean 
         mvn -B package --file pom.xml




